-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-merge-conflict
