{{- range $job := .Values.cronjobs }}
{{- if (eq $job.enabled true) }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $job.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: {{ $job.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ $job.name }}
            image: {{ $job.image }}
            env:
{{ toYaml $job.env | indent 12 -}}
          restartPolicy: {{ $job.restartPolicy }}
{{- end }}
{{- end }}