{{- if (eq .Values.cronjob.enabled true) }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            env:
            - name: FOO
              value: bar
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
{{- end }}