{{- range $secretId, $secret := .Values.secrets }}
{{- if $secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
{{ toYaml $secret.data | indent 2 -}}
{{- end }}
{{- end }}