{{- range $key, $api := .Values.apis }}
{{- if $api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $api.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $api.name }}
  ports:
  -
    name: http-{{ $api.name }}
    port: {{ $api.port }}
{{- end }}
{{- end }}