{{- range $api := .Values.apis }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $api.name }}
  namespace: {{ $.Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - mds-gateway
  http:
  - match:
    - uri:
        prefix: /{{ $api.name }}
    route:
    - destination:
        port:
          number: {{ $api.port }}
        host: {{ $api.name }}.{{ $.Values.namespace}}.svc.cluster.local
---
{{- end }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mds-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
