{{- if .Values.useAws }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/success-codes: "401"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
  labels:
    app: mds-core
spec:
  rules:
    - http:
        paths:
          {{- range $api := .Values.apis }}
          - path: {{ $api.pathPrefix }}/*
            backend:
              serviceName: {{ $api.name }}
              servicePort: {{ $api.port }}
          - path: {{ $api.pathPrefix }}
            backend:
              serviceName: {{ $api.name }}
              servicePort: {{ $api.port }}
          {{- end }}
---
{{- else }}
{{- range $api := .Values.apis }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $api.name }}
  namespace: {{ $.Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - mds-gateway
  http:
  - match:
    - uri:
        prefix: {{ $api.pathPrefix }}
    route:
    - destination:
        port:
          number: {{ $api.port }}
        host: {{ $api.name }}.{{ $.Values.namespace}}.svc.cluster.local
---
{{- end }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mds-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
{{- end }}
