apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-rw-external
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.host }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-ro-external
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.hostReader }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
