{{- range $api := .Values.apis }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $api.name }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $api.name }}
  ports:
  -
    name: http
    port: {{ $api.port }}
    targetPort: {{ $api.port }}
{{- end }}
