{{- if .Values.postgresql.internal }}
{{- else }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-rw-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.host }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
{{- if .Values.postgresql.hostReader }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-ro-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.hostReader }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
{{- if .Values.redis.host }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.redis.host }}
  ports:
  - number: {{ .Values.redis.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
{{- if .Values.fluentd.output.host }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: fluentbit-output
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.fluentd.output.host }}
  ports:
  - number: {{ .Values.fluentd.output.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
{{- end }}
