# !! File must end with empty line !!
dependencies:
  - name: redis
    version: 9.0.2
    repository: alias:stable
    condition: redis.internal
  - name: postgresql
    repository: alias:stable
    version: 6.2.1
    condition: postgresql.internal
  - name: fluentd
    version: 2.0.2
    repository: alias:stable
