dependencies:
  - name: grafana
    version: 1.2.5
    condition: grafana.enabled
  - name: prometheus
    version: 1.2.5
    condition: prometheus.enabled
  - name: tracing
    version: 1.2.5
    condition: tracing.enabled
#  - name: galley
#    version: 1.2.5
#    condition: galley.enabled
#  - name: kiali
#    version: 1.2.5
#    condition: kiali.enabled
#  - name: istiocoredns
#    version: 1.2.5
#    condition: istiocoredns.enabled
#  - name: certmanager
#    version: 1.2.5
#    condition: certmanager.enabled
