# !! File must end with empty line !!
dependencies:
  - name: redis
    repository: alias:stable
    condition: redis.enabled
  - name: postgresql
    repository: alias:stable
    condition: postgresql.enabled
  - name: kube-metrics-adapter
    repository: alias:banzaicloud-stable
