# !! File must end with empty line !!
dependencies:
  - name: redis
    version: 3.8.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
  - name: postgresql
    version: 3.13.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
