apis:
  - name: mds-provider
    pathPrefix: /provider
    port: 4000
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience: 
  - name: mds-agency
    pathPrefix: /agency
    port: 4001
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience: 
  - name: mds-audit
    pathPrefix: /audit
    port: 4002
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience: 
  - name: mds-policy
    pathPrefix: /policy
    port: 4003
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience: 
  - name: mds-compliance
    pathPrefix: /compliance
    port: 4004
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience: 
  - name: mds-daily
    pathPrefix: /daily
    port: 4005
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience: 
  - name: mds-native
    pathPrefix: /native
    port: 4006
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience: 
namespace: default
useJwtAuth: false
jwtIssuer: 
useAws: false
certificateArn: 
registry: 
useLatestImage: true
postgresql:
  internal: true
  name: mds
  user: mdsadmin
  host: host.docker.internal
  hostReader: host.docker.internal
  port: 5432
redis:
  internal: true
  host: host.docker.internal
  port: 6379
