apis:
  - name: mds-provider
    pathPrefix: /provider
    port: 4000
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-agency
    pathPrefix: /agency
    port: 4001
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-audit
    pathPrefix: /audit
    port: 4002
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-policy
    pathPrefix: /policy
    port: 4003
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-compliance
    pathPrefix: /compliance
    port: 4004
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-daily
    pathPrefix: /daily
    port: 4005
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-native
    pathPrefix: /native
    port: 4006
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-policy-author
    pathPrefix: /policy-author
    port: 4007
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
timezone: America/Los_Angeles
registry:
useLatestImage: true
tls:
  enabled: false
  domain:
  letsencrypt:
    enabled: false
    production: false
jwt:
  issuer:
  enabled: false
  audiences: []
postgresql:
  internal: true
  host:
  hostReader:
  port: 5432
  existingSecret: pg-pass
  postgresqlUsername: mdsadmin
  postgresqlDatabase: mds
  image:
    repository: postgres
    tag: 10
redis:
  internal: true
  host:
  port: 6379
  usePassword: false
  cluster:
    enabled: false
  master:
    disableCommands: []
  slave:
    disableCommands: []
